from enum import Enum

SCREEN_WIDTH = 3200
SCREEN_HEIGHT = 1800

ARENA_TILE_SIZE = 100 # Screen width and height need to be divisible by this

PLAYER_START_SPEED = 1.0

ALIEN_INCUBATION_TIME = 6.0
ALIEN_MAX_PACK_SIZE = 30
ALIEN_START_SPEED = 1.0

SPEED_INCREASE_ON_CONSUMING_HUMAN = 0.1

HUMAN_SPAWN_RATE = 5 # Per minute

CIVILIAN_START_SPEED = 0.7

MARINE_SPAWN_CHANCE = 0.2 # Civilian spawn chance is 1.0 - MARINE_SPAWN_CHANCE
MARINE_START_SPEED = 0.8

Direction = Enum('Direction', ['UP', 'UP_RIGHT', 'RIGHT', 'DOWN_RIGHT', 'DOWN', 'DOWN_LEFT', 'LEFT', 'UP_LEFT'])
